export const Config = {
  appName: 'bulblu',
  maxPhotos: 6,
  maxBioLength: 500,
  maxMessageLength: 2000,
  maxPostLength: 1000,
  maxCommentLength: 500,
  maxStoryDuration: 15,
  storyExpiryHours: 24,
  maxVoiceRoomParticipants: 50,
  superLikeLimit: 1,
  maxProfileViews: 50,
  paginationSize: 20,
  messagePageSize: 50,
  typingTimeoutMs: 3000,
  debounceMs: 300,
  maxFileSizeMB: 10,
  supportedImageTypes: ['image/jpeg', 'image/png', 'image/webp'],
  supportedVideoTypes: ['video/mp4', 'video/quicktime'],
  minAge: 18,
  maxAge: 100,
  maxInterests: 30,
  minInterests: 3,
} as const;
